<?xml version="1.0" encoding="UTF-8"?>
<!-- 
configuration to tests for User
-->
<!DOCTYPE capabilityrole [
<!ELEMENT capabilityrole (roles)>
<!ELEMENT roles (role*)>
<!ELEMENT role (capabilities, users?, groups?)>
<!ATTLIST role name ID #REQUIRED>
<!ELEMENT capabilities (capability+)>
<!ELEMENT users (user*)>
<!ELEMENT groups (group*)>
<!ELEMENT capability (#PCDATA)>
<!ELEMENT user (commands?)>
<!ATTLIST user name CDATA #REQUIRED>
<!ELEMENT group (commands?)>
<!ATTLIST group name CDATA #REQUIRED>
<!ELEMENT commands (command*)>
<!ELEMENT command (#PCDATA)>
]>
<capabilityrole>
  <roles>
    <role name="null">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <groups>
        <group name="null"/>
      </groups>
    </role>
    <role name="info0">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <users>
        <user name="%1$s"/>
      </users>
      <groups>
        <group name="%2$s"/>
      </groups>
    </role>
    <role name="info1">
      <capabilities>
        <capability>CAP_NET_RAW</capability>
      </capabilities>
      <users>
        <user name="%1$s"/>
      </users>
      <groups>
        <group name="%2$s"/>
      </groups>
    </role>
    <role name="info2">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <users>
        <user name="%1$s">
          <commands>
            <command>command1</command>
            <command>command2</command>
          </commands>
        </user>
      </users>
      <groups>
        <group name="%2$s">
          <commands>
            <command>command1</command> <!-- test no duplicate -->
            <command>command3</command> <!-- test if command1 command2 and command3 are available -->
          </commands>
        </group>
      </groups>
    </role>
    <role name="info3">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <users>
        <user name="%1$s"/>
      </users>
      <groups>
        <group name="%2$s">
          <commands>
            <command>command1</command> <!-- should ouput sr -c "command1" -->
            <command>command3</command>
          </commands>
        </group>
      </groups>
    </role>
    <role name="info4">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <users>
        <user name="%1$s">
          <commands>
            <command>command1</command> <!-- should ouput sr -c "command1" -->
            <command>command3</command>
          </commands>
        </user>
      </users>
      <groups>
        <group name="%2$s"/>
      </groups>
    </role>
  </roles>
</capabilityrole>
