<?xml version="1.0" encoding="UTF-8"?>
<!-- 
configuration to tests for User
-->
<!DOCTYPE capabilityrole [
<!ELEMENT capabilityrole (roles)>
<!ELEMENT roles (role*)>
<!ELEMENT role (capabilities, users?, groups?)>
<!ATTLIST role name ID #REQUIRED>
<!ELEMENT capabilities (capability+)>
<!ELEMENT users (user*)>
<!ELEMENT groups (group*)>
<!ELEMENT capability (#PCDATA)>
<!ELEMENT user (commands?)>
<!ATTLIST user name CDATA #REQUIRED>
<!ELEMENT group (commands?)>
<!ATTLIST group name CDATA #REQUIRED>
<!ELEMENT commands (command*)>
<!ELEMENT command (#PCDATA)>
]>
<capabilityrole>
  <roles>
    <role name="root">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <groups>
        <group name="%1$s"/>
      </groups>
    </role>
  </roles>
</capabilityrole>