<?xml version="1.0" encoding="UTF-8"?>
<!-- 
configuration to tests for Group
-->
<!DOCTYPE capabilityrole [
<!ELEMENT capabilityrole (roles)>
<!ELEMENT roles (role*)>
<!ELEMENT role (capabilities, users?, groups?)>
<!ATTLIST role name ID #REQUIRED>
<!ELEMENT capabilities (capability+)>
<!ELEMENT users (user*)>
<!ELEMENT groups (group*)>
<!ELEMENT capability (#PCDATA)>
<!ELEMENT user (commands?)>
<!ATTLIST user name CDATA #REQUIRED>
<!ELEMENT group (commands?)>
<!ATTLIST group name CDATA #REQUIRED>
<!ELEMENT commands (command*)>
<!ELEMENT command (#PCDATA)>
]>
<capabilityrole>
  <roles>
    <role name="role1">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <groups>
        <group name="%2$s"/>
      </groups>
    </role>
    <role name="role2"> <!-- role to test false-positives -->
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <users>
        <user name="gfoo">
          <commands>
            <command>echo role2-gfoo-cmd</command>
          </commands>
        </user>
        <user name="%1$s">
          <commands>
            <command>echo role2-user-cmd</command>
          </commands>
        </user>
      </users>
      <groups>
        <group name="gfoo">
          <commands>
            <command>echo role2-gfoo-cmd</command>
          </commands>
        </group>
        <group name="%2$s">
          <commands>
            <command>echo role2-group-cmd</command>
          </commands>
        </group>
      </groups>
    </role>
    <role name="role3">
      <capabilities>
        <capability>*</capability>
      </capabilities>
      <users>
        <user name="%1$s"/>
      </users>
    </role>
  </roles>
</capabilityrole>
